### ISSUE TITLE
Problem big variation in the sample rate

### ISSUE THREAD

**Issue by CyrielleAlbert** [kowalej/BlueMuse#11]
When I start streaming, after few seconds, the sample rate starts oscillating between low values (like 64) and high values (like 992). I've tried using another Muse and another computer but it's the same result. 
Does someone know where it could be from ?

**Comment by kowalej** [comment]
If it's the same issue with 2 Muses, and 2 different computers, perhaps it is the network that is bottle necking it?

**Comment by kowalej** [comment]
I'd also check the resource monitor on Windows while BlueMuse runs, see what kind of CPU and memory it's eating up, and compare with the system.

**Comment by kowalej** [comment]
Sorry that I can't be of more help, but I haven't heard this reported before, so these would be the places to start looking. I will say though that I have run BlueMuse on relatively low spec machines, and it has run with consistent sample rate.

**Comment by CyrielleAlbert** [comment]
Thank you for your answer. I'll check that.
