### ISSUE TITLE
Tried to install, the .cer has expired

### ISSUE THREAD

**Issue by jscodedeep** [kowalej/BlueMuse#14]

**Comment by kowalej** [comment]
@jscodedeep what version - cert should expire next year with the latest one. Unfortunately for dev certs I can only able to make them 1 year expiry.

**Comment by jscodedeep** [comment]
Thanks, found 1.1.1 version under TestDist. Was only looking under the Dist.

**Comment by oori** [comment]
Installing v1.1.1.0 from `TestDist`, I'm getting this error while installing manually.  installing certificate did work, this error comes later, while installing the app:

> Either you need a new certificate installed for this app package, or you need a new app package with trusted certificates. Your system administrator or the app developer can help. A certificate chain processed, but terminated in a root certificate which isn't trusted (0x800B0109)

<img width="513" alt="Screenshot 2019-10-04 at 22 37 06" src="https://user-images.githubusercontent.com/200688/66234993-b76a0500-e6f7-11e9-8f78-42a2ae1cf094.png">

**Comment by kowalej** [comment]
New version coming today will have 2 year valid cert expiring 2021.
