### ISSUE TITLE
pairing fails

### ISSUE THREAD

**Issue by francescacoo** [kowalej/BlueMuse#15]
Hi everyone,
it's a bit that I am trying to troubleshoot, but cannot solve the problem.

I have a muse 2016 (with one usb port).

The app can see it but couldn't connect.
I tried the exerimental forcing the pairing and it gives "connection failed".
![image](https://user-images.githubusercontent.com/1751355/66704878-7047c980-ed20-11e9-8b49-ccb3308a71ef.png)

I actually see the flashing lights change (fast moving for a while, and then a sort of different alternating cascading for another while).

I am trying also on ubuntu with pygatt but again, can detect the muse but can't connect.

Any idea on how I can troubleshoot?

Thanks!

**Comment by kowalej** [comment]
Sounds like your Muse is bugged out. 

First: Try holding the power button down for awhile, until you see the lights fade out. This should reset the device. Note: you might have to reset a couple times. 

Second: Try pairing it with the official Muse phone application. I believe they have some code in the official app that can fix a device in a "broken" pairing state.

If it can't even pair with the official app after several tries, I would personally consider swapping the device for a new one...
