### ISSUE TITLE
Muse (1) is visble but can't connect

### ISSUE THREAD

**Issue by nukadelic** [kowalej/BlueMuse#16]
I don't have the classic ( original ) muse with 2 usb ports, mine is a single usb port with a power button on the right side ( together with the LED lighs and the USB connections )

It will detect the device but will fail to connect 

![image](https://user-images.githubusercontent.com/6582633/68074975-40965980-fdd4-11e9-9e13-ccf51fa4752a.png)

**Edit**: here are my current settings:
* BlueMuse High Accuracy ( Unix ... )
* None - for - Secondary Time Step 
* Single precision (float32) - for - LSL Channel Data 
* [ NO ] - for - always pair
* [ NO ] - for - assume muse 2

Also using a fresh windows 10 install and never paired the device before to the OS

**Comment by nukadelic** [comment]
Just tried setting to always pair and it did try and connect but failed 

![image](https://user-images.githubusercontent.com/6582633/68075244-ca93f180-fdd7-11e9-941b-e640139b0aff.png)

**Comment by kowalej** [comment]
Start by trying to pair the device with your PC normally. Go to Start > Search "Bluetooth and Other Devices Settings" > Click "Add Bluetooth or other devices" > Bluetooth.

You may also try pairing your device with the official Muse app on a smartphone first - just to rule out connection issues with the unit itself.

Also try resetting the headset by holding down the power button for about 30 seconds.

**Comment by nukadelic** [comment]
It pairs with the official app on the smartphone, seems like its a windows issue, i won't find it before or after resetting the headset by holding the power button

**Comment by Zyx-Z-Y-X** [comment]
I got the same problem 
my MU-02 can connect to my phone apps , can connect and be detected by BlueMuse x64 on PC_2
BUT
can't be detected or visible on PC_1
BlueMuse x86
The log file say : 
  [Information] BlueMuse started.
  [date] [Error] Exception during find device (DeviceWatcher_Added) (device ID=BluetoothLE#BluetoothLE20: ...)

**Comment by nukadelic** [comment]
Dropped my headset, now its broken. I'm out, peace.
