### ISSUE TITLE
Bluemuse close automatically when i run it. 

### ISSUE THREAD

**Issue by LiemFrans** [kowalej/BlueMuse#2]

**Comment by kowalej** [comment]
What version?

**Comment by LiemFrans** [comment]
BlueMuse 1.0.8.0 .

**Comment by kowalej** [comment]
Try restarting PC.

**Comment by LiemFrans** [comment]
I've restarted it many times, but same.

**Comment by kowalej** [comment]
Hard for me to diagnose - maybe provide more system info. Also try these things:

1. You can try right clicking the app from Windows menu > More > App Settings > Repair. 
2. Reinstall the app - ensure old version(s) are removed.
3. See if there are log files:

C:\Users\{Username}\AppData\Local\Packages\07220b98-ffa5-4000-9f7c-e168a00899a6...\LocalState\Logs\BlueMuse-Log-{Timestamp}.log

LSLBridge:

C:\Users\{Username}\AppData\Local\Packages\07220b98-ffa5-4000-9f7c-e168a00899a6...\LocalCache\Local\Locgs\LSLBridge-Log-{Timestamp}.log

**Comment by LiemFrans** [comment]
this is bluemuse log
![image](https://user-images.githubusercontent.com/41262407/45133752-1ab9f880-b1c1-11e8-9cfb-9da25b10519b.png)

**Comment by kowalej** [comment]
You are trying to launch from command line eh?

**Comment by LiemFrans** [comment]
i trying in command line and trying to launch manual from start menu, but problem same.

**Comment by kowalej** [comment]
Looking at the error it seems there is something wrong with the device being found. Device ID is used after finding a Muse during search. Are you sure your Muse is a 2nd generation - Bluetooth LE version. Are you sure the Muse works with other device(s)/software?

**Comment by kowalej** [comment]
Do you have another Bluetooth device sitting around that has "Muse" in the name by any chance?

**Comment by LiemFrans** [comment]
![image](https://user-images.githubusercontent.com/41262407/45138371-5a3f0f80-b1d6-11e8-8f85-cc097cb7b02d.png)
this is my devices list connected on my pc.

**Comment by kowalej** [comment]
So I think the error is triggering from BluetoothManager.cs line 111:

![image](https://user-images.githubusercontent.com/1145056/45138882-00a9f700-b17c-11e8-8ce5-c3eb3d7f6db8.png)

I am able to force this error by putting some bad id data here when creating the BLE device object. Assuming this is where the error occurs on your machine - it is very strange that the device watcher would give a bad ID, considering it is supposed to find only BLE devices which are then filtered to make sure their name contains "Muse".

Just to make sure we are narrowing things down. Can you please try removing the Muse from your device list shown in the screenshot above and trying again.

**Comment by LiemFrans** [comment]
Thankyou verymuch,, your apps can launch again... :) 👍 
![image](https://user-images.githubusercontent.com/41262407/45139625-8fe5f780-b1da-11e8-9db1-3baa8fdfe624.png)

**Comment by kowalej** [comment]
As a note - add some try catch withing DeviceWatcher_Added method.
