### ISSUE TITLE
Where can i find contact Quality Electrode?

### ISSUE THREAD

**Issue by LiemFrans** [kowalej/BlueMuse#3]

**Comment by kowalej** [comment]
I don't understand what you are asking... could you be more clear - also how is this an issue with BlueMuse?

**Comment by LiemFrans** [comment]
its look like this in muse direct 
![image](https://user-images.githubusercontent.com/41262407/45249888-415b6900-b352-11e8-96c0-bd277739a182.png)

contact quality beetwen skin and electrode

**Comment by kowalej** [comment]
This app does not support or plan to support that feature right now.
