### ISSUE TITLE
Support for Muse S?

### ISSUE THREAD

**Issue by Venryx** [kowalej/BlueMuse#31]
Has anyone tried using (or updating) this software for the "Muse S" (latest Muse headset)?

For reference, someone got Muse S data-streaming working here (under muse-lsl repo): https://github.com/alexandrebarachant/muse-lsl/issues/120

**Comment by Venryx** [comment]
Nevermind, I've just confirmed it does work: ![](https://i.imgur.com/tpsjc7w.png)

**Comment by Venryx** [comment]
Oh also, I found this alternative which claims to work with all Muse headsets (haven't tried it myself yet): https://github.com/krigolson/uvicMuse

**Comment by kowalej** [comment]
@Venryx  - that's great news, I guess all that's left to do would be adding the device detection so under "Model" it says MuseS in the GUI.

**Comment by kowalej** [comment]
@Venryx if possible, could you test out my new prerelease (v2.1) which should detect the Muse S (it won't show up as "Muse2" any more). https://github.com/kowalej/BlueMuse/releases/download/v2.1/BlueMuse_2.1.0.0.zip

**Comment by Venryx** [comment]
Unfortunately, version 2.1.0.0 still thinks it is a Muse2:
![](https://i.imgur.com/aMUtuTO.png)

Not sure what method is used to distinguish between Muse2 and MuseS, though it seems you could just parse the device-name, checking whether it starts with "MuseS". (perhaps you're already doing this and the issue just lies somewhere else)

**Comment by kowalej** [comment]
Hey sorry I think there was an error in that release code, I uploaded another one - same link, don't want to waste your time, but feel free to try again if possible. Been trying to get this fixed, but unfortunately I don't own a Muse S to check myself :)

**Comment by Venryx** [comment]
Yep, it works now:
![](https://i.imgur.com/muJOpBf.png)

**Comment by kowalej** [comment]
Thanks.
