### ISSUE TITLE
Can we get other data like the horseshoe status? 

### ISSUE THREAD

**Issue by tcmxx** [kowalej/BlueMuse#32]
Hello,

BlueMuse is awesome~ I can get the data easily using LSL. 

But I notice that there is no horseshoe status or the processed eeg (Theta, Alpha ..) and so one.

Are those data from Muse directly (especially the horseshoe status), and how can we get them?

Thanks  lot!
Xiaoxiao

**Comment by kowalej** [comment]
This was discussed in #23 - basically the data doesn't come directly from Muse. If I had a lot of free time I would add some processing in the app, but this is not in the cards right now.
