### ISSUE TITLE
Streaming from multiple Muses to same computer

### ISSUE THREAD

**Issue by sunshineinsandiego** [kowalej/BlueMuse#45]
Hi - Wondering if BlueMuse allows for streaming multiple muses simultaneously to the same computer and then recording all streams to LabRecorder. Does this require opening multiple instances of BlueMuse i.e. one instance for each headset, or is this possible using a single instance of BlueMuse to multiple headsets? Understand that in the FAQs there may be issues with time synchronicity for streaming multiple headsets. Advice? Thanks!

**Comment by mmestucci** [comment]
Hi @sunshineinsandiego yes, BlueMuse allows to connect and to stream multiple devices. 

I'm trying a setup with 2x Muse 2 connected to the same pc using BlueMuse and it works. 

Just pay attention about the rate: I tested it with different machines and it works well just on powerful Dell laptop ...
![Screenshot 2021-07-16 at 16 34 57](https://user-images.githubusercontent.com/7244310/125965336-83af07c0-45bd-431a-8b50-ae35248093a0.png)

**Comment by sunshineinsandiego** [comment]
Got it, thank you! Appreciate the help.
