### ISSUE TITLE
How can i connect and stream in BlueMuse while i connect to MuseDirect for check Quality Contact?

### ISSUE THREAD

**Issue by LiemFrans** [kowalej/BlueMuse#5]

**Comment by kowalej** [comment]
You can't connect to both at once. You could check with MuseDirect first then disconnect, and go to BlueMuse to produce stream. 

What I would recommend is to perhaps use a library to analyze the data to determine signal quality on t he actual LSL stream if you want a sort of "all-in-one" solution.
