### ISSUE TITLE
Question about PPG channels

### ISSUE THREAD

**Issue by guz6** [kowalej/BlueMuse#58]
Hi, I researched online and I didn't find any explaination. There are three PPG channels: Ambient, Infrared, Red. What is the meaing of these three channels? If I want to calculate heart rate. Which channel I need to focus? Thank you very much.

**Comment by corteXnzt** [comment]
Hi are you able to calculate the HR from any of that channels?

**Comment by kowalej** [comment]
You'd want to focus on red / infrared channels. Calculating heart rate is possible, but not a trivial task. You'll likely need to develop a regression model to do this using sample data collected from users wearing heart rate monitor. You can good papers that have done similar.
