### ISSUE TITLE
data in LSL stream

### ISSUE THREAD

**Issue by Mickey675** [kowalej/BlueMuse#9]
Does this application only stream the EEG data, or does it also support the accelerometer data that the muse provides? I'm streaming into matlab and I only see the EEG channels.

Thanks

**Comment by kowalej-homex** [comment]
@Mickey675 just the EEG right now - if I find the time I'd like to add the other data...

**Comment by kowalej** [comment]
@Mickey675  Only the EEG right now - if I find the time I'd like to add the other data as well though.
